POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNvb2xtYW4xMjMiLCJpZCI6IjVmN2Y1NzZiYTU0N2MxNTI3Y2E0NWI3YiIsImlhdCI6MTYwMjE4MTUyMH0.GuS_NzNj3QIgQQ5iVEgCZWOSwMt2pp0Be3qR5j9zb3s

{
  "title": "Cool man things to do",
  "author": "Author111",
  "url": "coolurl.com999",
  "userId": "5f7f576ba547c1527ca45b7b",
  "likes" : 5000
}
